version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - network
    depends_on:
      - mysql
      - redis
  
  node:
    image: node:18
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - network
    command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx:alpine
    container_name: server
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: missionCTRL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

  redis:
    image: redis:alpine
    container_name: queue
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mysql_data:
    driver: local